language: csharp
solution: soen341.sln
install:
  - nuget restore src/soen341Tests/packages.config -SolutionDirectory src
  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug soen341.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./soen341Tests/bin/Debug/soen341Tests.dll
