language: csharp
solution: soen341.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore ./soen341.sln -PackagesDirectory /soen341/packages -Verbosity detailed
  - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug soen341.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./soen341Tests/bin/Debug/soen341Tests.dll
